name: 'courses.yasharu.com github pages'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache npm
      id: courses-yasharu-com-npm-cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
    - run: npm i -E ; npm run github-pages
    - name: Deploy 🚀 GitHub Pages build
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: src/.vuepress/dist # The folder the action should deploy.
